name: Deploy to GCF

on:
  push:
    branches:
      - 'poc/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Deploy to Cloud Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'integration-poc'
          runtime: 'python39'
          entry_point: 'gcf_handler'
          region: 'australia-southeast1' 
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          env_vars: |
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
 